export const topAnime = [
  {
    id: 1,
    title: "Saga of Tanya the evil",
    description:
      "A girl with blond hair, blue eyes, and porcelain skin fights on the front lines of a brutal war and climbs the ranks of the imperial army.",
    image: "/src/assets/img/card1.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 7.6,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 2,
    title: "86",
    description:
      "The Republic of San Magnolia has been attacked by its neighbor, the Empire.",
    image: "/src/assets/img/card2.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.2,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 3,
    title: "Solo Leveling",
    description:
      "Follows the adventures of Sung Jinwoo in a world that is constantly threatened by monsters and evil forces. In his battles Sung transforms himself from the weakest hunter of all mankind to one of the strongest hunters in existence.",
    image: "/src/assets/img/card3.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.4,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 4,
    title: "Monster",
    description:
      "Tenma, a brilliant neurosurgeon with a promising future, risks his career to save the life of a critically wounded young boy. The boy, now a charismatic young man, reappears 9 years later in the midst of a string of unusual serial murders.",
    image: "/src/assets/img/card1.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.7,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 5,
    title: "Chainsaw Man",
    description:
      "Following a betrayal, a young man left for dead is reborn as a powerful devil-human hybrid after merging with his pet devil and is soon enlisted into an organization dedicated to hunting devils.",
    image: "/src/assets/img/card2.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.3,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 6,
    title: "One Punch Man: Wanpanman",
    description:
      "The story of Saitama, a hero that does it just for fun & can defeat his enemies with a single punch.",
    image: "/src/assets/img/card3.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.7,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 7,
    title: "Kiseijû: Sei no kakuritsu",
    description:
      "17-year-old Shinichi Izumi is partially infected by a Parasyte, monsters that butcher and consume humans. He must learn to co-exist with the creature if he is to survive both the life of a Parasyte and a human as part monster, part person.",
    image: "/src/assets/img/card1.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.3,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 8,
    title: "Death Note: Desu nôto",
    description:
      "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
    image: "/src/assets/img/card2.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.9,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
  {
    id: 9,
    title: "Dororo",
    description:
      "Sightless Hyakkimaru wields fearsome prosthetics in place of the limbs his father traded to 12 demons. When he encounters the young thief Dororo, the pair sets out to reclaim Hyakkimaru's body parts and survive the demon-infested world.",
    image: "/src/assets/img/card3.png",
    trailer: "/src/assets/vid/test.mp4",
    rating: 8.2,
    genre: "Экшен",
    country: "Япония",
    actors: "Актёр 1, Актёр 2",
    writers: "Сценарист 1",
    date: "2023-01-01",
    age: "16+",
    stars: 7,
  },
];
